[Fix] ValueError: could not convert string to float: None
File "/home/ibiam/Activities/convert/activity.py", line 201, in _call
    self._update_label()
  File "/home/ibiam/Activities/convert/activity.py", line 193, in _update_label
    new_convert = locale.format(fmt, float(convert_value))
ValueError: could not convert string to float: None

Error caused by active returning a negative value which then returns None,
setting active to zero instead of returning None fixes the error.